export const HomePageData = [
  { village_name: "Bel-Air", city_name: "Makati" },
  { village_name: "Dasmariñas Village", city_name: "Makati" },
  { village_name: "Greenhills", city_name: "San Juan" },
  { village_name: "BF Homes", city_name: "Parañaque" },
  { village_name: "Ayala Alabang", city_name: "Muntinlupa" },
  { village_name: "La Vista", city_name: "Quezon City" },
  { village_name: "Loyola Grand Villas", city_name: "Quezon City" },
  { village_name: "North Bay Boulevard", city_name: "Navotas" },
  { village_name: "Marulas", city_name: "Valenzuela" },
  { village_name: "Pinagkaisahan", city_name: "Taguig" },
  { village_name: "Fort Bonifacio", city_name: "Taguig" },
  { village_name: "Don Bosco", city_name: "Parañaque" },
  { village_name: "Acacia Estates", city_name: "Taguig" },
  { village_name: "Tandang Sora", city_name: "Quezon City" },
  { village_name: "Addition Hills", city_name: "Mandaluyong" },
  { village_name: "Malibay", city_name: "Pasay" },
  { village_name: "Ugong", city_name: "Pasig" },
  { village_name: "Baclaran", city_name: "Parañaque" },
  { village_name: "San Antonio", city_name: "Makati" },
  { village_name: "Commonwealth", city_name: "Quezon City" },
];
