export const HomePageData = [
  { village_name: "Bel-Air", city_name: "Makati", image1: "/assets/bel-air_village.jpg" },
  { village_name: "Dasmariñas Village", city_name: "Makati", image1: "/assets/dasma-village.jpg" },
  { village_name: "Greenhills", city_name: "San Juan", image1: "/assets/greehills-village.jpg" },
  { village_name: "BF Homes", city_name: "Parañaque", image1: "/assets/bf-homes_village.jpg" },
  { village_name: "Ayala Alabang", city_name: "Muntinlupa", image1: "/assets/ayala-alabang_village.jpg" },
  { village_name: "La Vista", city_name: "Quezon City", image1: "/assets/La-Vista_Village.jpg" },
  { village_name: "Loyola Grand Villas", city_name: "Quezon City", image1: "/assets/Loyala-Grand_village.jpg" },
  { village_name: "North Bay Boulevard", city_name: "Navotas", image1: "/assets/NorthBay-village.png" },
  { village_name: "Marulas", city_name: "Valenzuela", image1: "/assets/marulas_village.jpg" },
  { village_name: "Pinagkaisahan", city_name: "Taguig", image1: "/assets/Pinagkaisahan_Village" },
  { village_name: "Fort Bonifacio", city_name: "Taguig", image1: "/assets/fort-bonifacio.jpg" },
  { village_name: "Don Bosco", city_name: "Parañaque", image1: "/assets/don-bosco_village.jpg" },
  { village_name: "Acacia Estates", city_name: "Taguig", image1: "/assets/Acacia-Estates_village.jpg" },
  { village_name: "Tandang Sora", city_name: "Quezon City", image1: "/assets/tandang-sora_village.jpg" },
  { village_name: "Addition Hills", city_name: "Mandaluyong", image1: "/assets/addition-hills_village.jpg" },
  { village_name: "Malibay", city_name: "Pasay", image1: "/assets/malibay_village.jpg" },
  { village_name: "Ugong", city_name: "Pasig", image1: "/assets/ugong_village.jpg" },
  { village_name: "Baclaran", city_name: "Parañaque", image1: "/assets/baclaran_image.jpg" },
  { village_name: "San Antonio", city_name: "Makati", image1: "/assets/san-antonio_village.jpg" },
  { village_name: "Commonwealth", city_name: "Quezon City", image1: "/assets/commonwealth_village.jpg" },
];
